const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Plugins.Button,
		C3.Plugins.progressbar,
		C3.Plugins.Text,
		C3.Plugins.Shape3D,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.progressbar.Acts.SetProgress,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Acts.SetText
	];
};
self.C3_JsPropNameTable = [
	{background: 0},
	{score: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{health: 0},
	{"8Direction": 0},
	{Sine: 0},
	{chQasim: 0},
	{Bullet: 0},
	{enemy: 0},
	{Sprite4: 0},
	{restartButton: 0},
	{Sprite5: 0},
	{Button: 0},
	{BackToStart: 0},
	{Healthbar: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{scoreshower: 0},
	{scoredas: 0},
	{scoreDas: 0},
	{spritesheetdouble: 0},
	{"3DShape": 0},
	{Sprite8: 0},
	{finalScoreText: 0},
	{playerhealthvalue: 0},
	{playerscore: 0}
];

self.InstanceType = {
	background: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	chQasim: class extends self.ISpriteInstance {},
	enemy: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	restartButton: class extends self.IButtonInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	BackToStart: class extends self.IButtonInstance {},
	Healthbar: class extends self.IProgressBarInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	scoreshower: class extends self.ITextInstance {},
	scoreDas: class extends self.ITextInstance {},
	spritesheetdouble: class extends self.ISpriteInstance {},
	_3DShape: class extends self.I3DShapeInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	finalScoreText: class extends self.ITextInstance {}
}